
//! Autogenerated weights for `robonomics_xcm_info`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-06-05, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `nano`, CPU: `11th Gen Intel(R) Core(TM) i5-1130G7 @ 1.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/dev-runtime/dev_runtime.wasm
// --pallet
// robonomics-xcm-info
// --extrinsic
//
// --output
// weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions.
pub trait WeightInfo {
	fn set_relay_network() -> Weight;
	fn set_asset_link() -> Weight;
}

/// Weight functions for `robonomics_xcm_info`.
// pub struct WeightInfo<T>(PhantomData<T>);
// impl<T: frame_system::Config> robonomics_xcm_info::WeightInfo for WeightInfo<T> {
pub struct RobonomicsWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for RobonomicsWeight<T> {
	/// Storage: `XcmInfo::RelayNetwork` (r:0 w:1)
	/// Proof: `XcmInfo::RelayNetwork` (`max_values`: Some(1), `max_size`: Some(41), added: 536, mode: `MaxEncodedLen`)
	fn set_relay_network() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_829_000 picoseconds.
		Weight::from_parts(10_437_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XcmInfo::AssetIdOf` (r:0 w:1)
	/// Proof: `XcmInfo::AssetIdOf` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `XcmInfo::LocationOf` (r:0 w:1)
	/// Proof: `XcmInfo::LocationOf` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	fn set_asset_link() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_100_000 picoseconds.
		Weight::from_parts(17_546_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
